// Generated by Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
/**
*/
typedef SWIFT_ENUM(NSInteger, BannerTemplateCustomClickModes) {
  BannerTemplateCustomClickModesWholeBanner = 0,
  BannerTemplateCustomClickModesButton = 1,
};

@class NSCoder;
@class UITouch;
@class UIEvent;

/**
  A star rating view that can be used to show customer rating for the products. On can select stars by tapping on them when updateOnTouch settings is true. An optional text can be supplied that is shown on the right side.
  Example:
  cosmosView.rating = 4
  cosmosView.text = “(123)”
  Shows: ★★★★☆ (132)
*/
SWIFT_CLASS("_TtC12HADFramework10CosmosView")
@interface CosmosView : UIView
/**
  The currently shown number of stars, usually between 1 and 5. If the value is decimal the stars will be shown according to the Fill Mode setting.
*/
@property (nonatomic) double rating;
/**
  Currently shown text. Set it to nil to display just the stars without text.
*/
@property (nonatomic, copy) NSString * _Nullable text;
/**
  Draws the stars when the view comes out of storyboard with default settings
*/
- (void)awakeFromNib;
/**
  Initializes and returns a newly allocated cosmos view object.
*/
- (nonnull instancetype)init;
/**
  Initializes and returns a newly allocated cosmos view object with the specified frame rectangle.
  \param frame The frame rectangle for the view.

*/
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/**
  Initializes and returns a newly allocated cosmos view object.
*/
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/**
  Updates the stars and optional text based on current values of \code
  rating
  \endcode and \code
  text
  \endcode properties.
*/
- (void)update;
/**
  Returns the content size to fit all the star and text layers.
*/
@property (nonatomic, readonly) CGSize intrinsicContentSize;
/**
  Called by the system in accessibility voice-over mode when the value is incremented by the user.
*/
- (void)accessibilityIncrement;
/**
  Called by the system in accessibility voice-over mode when the value is decremented by the user.
*/
- (void)accessibilityDecrement;
/**
  Closure will be called when user touches the cosmos view. The touch rating argument is passed to the closure.
*/
@property (nonatomic, copy) void (^ _Nullable didTouchCosmos)(double);
/**
  Closure will be called when the user lifts finger from the cosmos view. The touch rating argument is passed to the closure.
*/
@property (nonatomic, copy) void (^ _Nullable didFinishTouchingCosmos)(double);
/**
  Overriding the function to detect the first touch gesture.
*/
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
/**
  Overriding the function to detect touch move.
*/
- (void)touchesMoved:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
/**
  Detecting event when the user lifts their finger.
*/
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
/**
  Increase the hitsize of the view if it’s less than 44px for easier touching.
*/
- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent * _Nullable)event;
/**
  Draw the stars in interface buidler
*/
- (void)prepareForInterfaceBuilder;
@end


/**
*/
SWIFT_CLASS("_TtC12HADFramework3HAD")
@interface HAD : NSObject
/**
*/
+ (void)create;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/**
*/
typedef SWIFT_ENUM(NSInteger, HADAdContent) {
  HADAdContentTitle = 0,
  HADAdContentDescription = 1,
  HADAdContentBanner = 2,
  HADAdContentIcon = 3,
};

/**
*/
typedef SWIFT_ENUM(NSInteger, HADAdOrientation) {
  HADAdOrientationPortrait = 0,
  HADAdOrientationLandscape = 1,
};

/**
*/
typedef SWIFT_ENUM(NSInteger, HADAdType) {
  HADAdTypeNative = 0,
  HADAdTypeHtml = 1,
  HADAdTypeInterstitial = 2,
};

/**
*/
typedef SWIFT_ENUM(NSInteger, HADBannerSize) {
  HADBannerSizeBlock300x250 = 0,
  HADBannerSizeHeight50 = 1,
  HADBannerSizeHeight90 = 2,
};

/**
*/
typedef SWIFT_ENUM(NSInteger, HADBannerTemplateTypes) {
  HADBannerTemplateTypesBlockOne = 0,
  HADBannerTemplateTypesBlockTwo = 1,
  HADBannerTemplateTypesBlockThree = 2,
  HADBannerTemplateTypesLineOne = 3,
  HADBannerTemplateTypesLineTwo = 4,
  HADBannerTemplateTypesLineThree = 5,
};

@protocol HADBannerTemplateViewDelegate;
@class UIColor;

/**
  Banner template view
*/
SWIFT_CLASS("_TtC12HADFramework21HADBannerTemplateView")
@interface HADBannerTemplateView : UIView
/**
*/
@property (nonatomic) BOOL refresh;
/**
*/
@property (nonatomic) uint32_t refreshTime;
/**
*/
- (void)drawRect:(CGRect)rect;
/**
*/
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/**
*/
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/**
*/
- (void)removeFromSuperview;
/**
*/
- (void)loadAdWithPlacementId:(NSString * _Nonnull)placementId bannerTemplate:(enum HADBannerTemplateTypes)bannerTemplate delegate:(id <HADBannerTemplateViewDelegate> _Nullable)delegate;
/**
*/
- (void)layoutSubviews;
/**
*/
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
/**
*/
@property (nonatomic, strong) UIColor * _Nullable customTitleTextColor;
/**
*/
@property (nonatomic, strong) UIColor * _Nullable customDescriptionTextColor;
/**
*/
@property (nonatomic, strong) UIColor * _Nullable customPoweredByTextColor;
/**
*/
@property (nonatomic, strong) UIColor * _Nullable customAgeRatingTextColor;
/**
*/
@property (nonatomic, strong) UIColor * _Nullable customAgeRatingBackgroundColor;
/**
*/
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
/**
*/
@property (nonatomic, strong) UIColor * _Nullable customBackgroundColor;
/**
*/
@property (nonatomic) CGFloat customBannerCornerRadius;
/**
*/
@property (nonatomic) CGFloat customIconCornerRadius;
/**
*/
@property (nonatomic) CGFloat customAgeRatingCornerRadius;
/**
*/
@property (nonatomic) CGFloat customButtonCornerRadius;
/**
*/
@property (nonatomic, strong) UIColor * _Nullable customButtonTitleColor;
/**
*/
@property (nonatomic, strong) UIColor * _Nullable customButtonBackgroundColor;
/**
*/
@property (nonatomic, strong) UIColor * _Nullable customButtonBorderColor;
/**
*/
@property (nonatomic) CGFloat customButtonBorderWidth;
/**
*/
- (void)setButtonSideMarginsWithMargin:(CGFloat)margin;
/**
*/
@property (nonatomic, strong) UIColor * _Nullable customStarRatingTextColor;
/**
*/
@property (nonatomic, strong) UIColor * _Nullable customStarRatingFilledColor;
/**
*/
@property (nonatomic, strong) UIColor * _Nullable customStarRatingEmptyColor;
/**
*/
@property (nonatomic) enum BannerTemplateCustomClickModes customClickMode;
@end

@class NSError;

/**
*/
SWIFT_PROTOCOL("_TtP12HADFramework29HADBannerTemplateViewDelegate_")
@protocol HADBannerTemplateViewDelegate
@optional
- (void)HADTemplateViewWithView:(HADBannerTemplateView * _Nonnull)view didFailWithError:(NSError * _Nullable)error;
- (void)HADTemplateViewDidLoadWithView:(HADBannerTemplateView * _Nonnull)view;
- (void)HADTemplateViewDidClickWithView:(HADBannerTemplateView * _Nonnull)view;
@end

@protocol HADBannerViewDelegate;

/**
  Banner view
*/
SWIFT_CLASS("_TtC12HADFramework13HADBannerView")
@interface HADBannerView : UIView
/**
*/
@property (nonatomic) uint32_t refreshTime;
/**
*/
- (void)drawRect:(CGRect)rect;
/**
*/
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/**
*/
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/**
*/
- (void)removeFromSuperview;
/**
*/
- (void)loadAdWithPlacementId:(NSString * _Nonnull)placementId bannerSize:(enum HADBannerSize)bannerSize delegate:(id <HADBannerViewDelegate> _Nullable)delegate;
/**
*/
- (void)layoutSubviews;
/**
*/
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
@end


/**
*/
SWIFT_PROTOCOL("_TtP12HADFramework21HADBannerViewDelegate_")
@protocol HADBannerViewDelegate
@optional
- (void)HADViewWithView:(HADBannerView * _Nonnull)view didFailWithError:(NSError * _Nullable)error;
- (void)HADViewDidLoadWithView:(HADBannerView * _Nonnull)view;
- (void)HADViewDidClickWithView:(HADBannerView * _Nonnull)view;
@end

enum HADEventType : NSInteger;

/**
  HAD Event manager
*/
SWIFT_CLASS("_TtC12HADFramework8HADEvent")
@interface HADEvent : NSObject
/**
*/
+ (void)sendWithEvent:(enum HADEventType)type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/**
*/
typedef SWIFT_ENUM(NSInteger, HADEventType) {
  HADEventTypeRegistration = 101,
  HADEventTypeLogin = 102,
  HADEventTypeOpen = 103,
  HADEventTypeAddToWishlist = 201,
  HADEventTypeAddToCart = 202,
  HADEventTypeAddedPaymentInfo = 203,
  HADEventTypeReservation = 204,
  HADEventTypeCheckoutInitiated = 205,
  HADEventTypePurchase = 206,
  HADEventTypeSearch = 301,
  HADEventTypeContentView = 302,
  HADEventTypeTutorialCompleted = 401,
  HADEventTypeLevelAchieved = 402,
  HADEventTypeAchievementUnlocked = 403,
  HADEventTypeSpentCredit = 404,
  HADEventTypeInvite = 501,
  HADEventTypeRated = 502,
  HADEventTypeShare = 503,
};

@class HADNativeAd;

/**
*/
SWIFT_PROTOCOL("_TtP12HADFramework19HADNativeAdDelegate_")
@protocol HADNativeAdDelegate
@optional
- (void)HADNativeAdDidFailWithNativeAd:(HADNativeAd * _Nonnull)nativeAd error:(NSError * _Nonnull)error;
- (void)HADNativeAdDidLoadWithNativeAd:(HADNativeAd * _Nonnull)nativeAd;
- (void)HADNativeAdDidClickWithNativeAd:(HADNativeAd * _Nonnull)nativeAd;
@end

@protocol HADInterstitialDelegate;
@class NSBundle;

/**
  Interstitial view controller implementation
*/
SWIFT_CLASS("_TtC12HADFramework15HADInterstitial")
@interface HADInterstitial : UIViewController <HADNativeAdDelegate>
/**
*/
@property (nonatomic, strong) id <HADInterstitialDelegate> _Nullable delegate;
/**
*/
- (nonnull instancetype)initWithPlacementId:(NSString * _Nonnull)placementId OBJC_DESIGNATED_INITIALIZER;
/**
*/
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/**
*/
- (void)setPlacementIdWithPlacementId:(NSString * _Nonnull)placementId;
/**
*/
- (void)viewDidLoad;
/**
*/
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
/**
*/
@property (nonatomic, readonly) UIInterfaceOrientation preferredInterfaceOrientationForPresentation;
/**
*/
- (void)viewWillAppear:(BOOL)animated;
/**
*/
- (void)viewWillDisappear:(BOOL)animated;
/**
*/
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
/**
*/
- (void)loadAd;
/**
*/
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
/**
*/
- (void)HADNativeAdDidLoadWithNativeAd:(HADNativeAd * _Nonnull)nativeAd;
/**
*/
- (void)HADNativeAdDidClickWithNativeAd:(HADNativeAd * _Nonnull)nativeAd;
/**
*/
- (void)HADAd:(HADNativeAd * _Nonnull)nativeAd didFailWithError:(NSError * _Nonnull)error;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


/**
*/
SWIFT_PROTOCOL("_TtP12HADFramework23HADInterstitialDelegate_")
@protocol HADInterstitialDelegate
@optional
- (void)HADInterstitialDidFailWithController:(HADInterstitial * _Nonnull)controller error:(NSError * _Nullable)error;
- (void)HADInterstitialDidLoadWithController:(HADInterstitial * _Nonnull)controller;
- (void)HADInterstitialDidClickWithController:(HADInterstitial * _Nonnull)controller;
- (void)HADInterstitialDidCloseWithController:(HADInterstitial * _Nonnull)controller;
- (void)HADInterstitialWillCloseWithController:(HADInterstitial * _Nonnull)controller;
@end

@class UIImage;

/**
*/
SWIFT_CLASS("_TtC12HADFramework12HADMediaView")
@interface HADMediaView : UIView
/**
*/
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
/**
*/
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/**
*/
- (void)drawRect:(CGRect)rect;
/**
*/
- (void)loadHADBannerWithNativeAd:(HADNativeAd * _Nullable)nativeAd animated:(BOOL)animated completion:(void (^ _Nullable)(NSError * _Nullable, UIImage * _Nullable))completion;
/**
*/
- (void)loadHADIconWithNativeAd:(HADNativeAd * _Nullable)nativeAd animated:(BOOL)animated completion:(void (^ _Nullable)(NSError * _Nullable, UIImage * _Nullable))completion;
@end

@class UIImageView;

/**
*/
SWIFT_CLASS("_TtC12HADFramework11HADNativeAd")
@interface HADNativeAd : NSObject
/**
*/
@property (nonatomic, strong) id <HADNativeAdDelegate> _Nullable delegate;
/**
*/
@property (nonatomic, copy) NSString * _Nullable title;
/**
*/
@property (nonatomic, copy) NSString * _Nullable desc;
/**
*/
@property (nonatomic, copy) NSString * _Nullable adTopic;
/**
*/
@property (nonatomic, copy) NSString * _Nullable ageRating;
/**
*/
@property (nonatomic, copy) NSString * _Nullable ratingsCount;
/**
*/
@property (nonatomic, copy) NSString * _Nullable cta;
/**
  Initialization
*/
- (nonnull instancetype)initWithPlacementId:(NSString * _Nonnull)placementId delegate:(id <HADNativeAdDelegate> _Nullable)delegate OBJC_DESIGNATED_INITIALIZER;
/**
*/
- (void)loadAd;
/**
*/
- (void)loadIconInto:(UIImageView * _Nonnull)imageView animated:(BOOL)animated;
/**
*/
- (void)loadBannerInto:(UIImageView * _Nonnull)imageView animated:(BOOL)animated;
/**
*/
- (void)handleClick;
/**
*/
+ (NSString * _Nonnull)sdkVersion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end



@interface UIView (SWIFT_EXTENSION(HADFramework))
@end

#pragma clang diagnostic pop
